--- 
after_success: 
  - "docker build -t hamzamirza/docker-react-app-client-image -f ./client/dockerfile ./client"
  - "docker build -t hamzamirza/docker-react-app-nginx-image -f ./nginx/dockerfile ./nginx"
  - "docker build -t hamzamirza/docker-react-app-server-image -f ./server/dockerfile ./server"
  - "docker build -t hamzamirza/docker-react-app-worker-image -f ./worker/dockerfile ./worker"
  - "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERID\" --password-stdin"
  - "docker push hamzamirza/docker-react-app-client-image"
  - "docker push hamzamirza/docker-react-app-nginx-image"
  - "docker push hamzamirza/docker-react-app-server-image"
  - "docker push hamzamirza/docker-react-app-worker-image"
before_install: 
  - "docker build -t hamzamirza/docker-react-app-test-image -f ./client/dockerfile.dev ./client"
script: 
  - "docker run -e=CI=true hamzamirza/docker-react-app-test-image npm run test"
services: 
  - docker
sudo: required

